[package]
name = "dust"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
pest = "2.7.11"
pest_derive = "2.7.11"
rand = "0.8.5"
rustyline = "14.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
